Controllers/AlunoController.cs
using beforza.Models;
using beforza.Repository.Implamentations;
using beforza.Repository.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace beforza.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoRepository _alunoRepository = new AlunoRepository();
        // GET: Aluno
        public ActionResult Index(string searchBy, string search, int? page)
        {
            var alunos = _alunoRepository.GetAll();
            return View(alunos.ToPagedList(page ?? 1, 10));
        }

        // GET: Aluno/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Aluno/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aluno/Create
        [HttpPost]
        public ActionResult Create(AlunoModel model)
        {
            model.AcademiaId = 1;
            model.Ativo = true;
            _alunoRepository.Add(model);
            return View();
        }

        // GET: Aluno/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Aluno/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Aluno/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Aluno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ExercicioController.cs
using beforza.Models;
using beforza.Repository.Implamentations;
using beforza.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace beforza.Controllers
{
    public class ExercicioController : Controller
    {
        private readonly IExercicioRepository _exercicioRepository = new ExercicioRepository();
        // GET: Exercicio
        public ActionResult Index(string searchBy, string search, int? page)
        {
            var exercicios = _exercicioRepository.GetAll();
            return View(exercicios.ToPagedList(page ?? 1, 10));
        }

        // GET: Exercicio/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Exercicio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exercicio/Create
        [HttpPost]
        public ActionResult Create(ExercicioModel model)
        {
            model.Ativo = true;
            _exercicioRepository.Add(model);
            return View();
        }

        // GET: Exercicio/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Exercicio/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Exercicio/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Exercicio/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TreinoController.cs
using beforza.Models;
using beforza.Repository.Implamentations;
using beforza.Repository.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace beforza.Controllers
{
    public class TreinoController : Controller
    {
        private readonly ITreinoRepository _treinoRepository = new TreinoRepository();
        private readonly IAlunoRepository _alunoRepository = new AlunoRepository();
        private readonly IAcademiaRepository _academiaRepository = new AcademiaRepository();

        // GET: Treino
        public ActionResult Index(string searchBy, string search, int? page)
        {
            var treinosView = _treinoRepository.GetAll();
            return View(treinosView.ToPagedList(page ?? 1, 10));
        }

        // GET: Treino/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Treino/Create
        [HttpPost]
        public ActionResult Create(TreinoModel treino)
        {
            var academia = _academiaRepository.GetById(1);

            treino.AcademiaId = academia.AcademiaId;

            _treinoRepository.Add(treino);


            return View();
        }

        // GET: Treino/Edit/5
        public ActionResult Edit(int id)
        {
            var treino = _treinoRepository.GetByIdEager(id);
            return View(treino);
        }

        // POST: Treino/Edit/5
        [HttpPost]
        public ActionResult Edit(TreinoModel treino)
        {
            //treino.TreinoId = 1002;
            _treinoRepository.Update(treino);
            return View(treino);
        }

        [HttpGet]
        public ActionResult TreinoToAluno()
        {
            ViewBag.TreinoId = new SelectList(_treinoRepository.GetAll(), "TreinoId", "Nome");
            ViewBag.AlunoId = new SelectList(_alunoRepository.GetAll(), "AlunoId", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult TreinoToAluno(int TreinoId, int AlunoId)
        {
            ViewBag.TreinoId = new SelectList(_treinoRepository.GetAll(), "TreinoId", "Nome");
            ViewBag.AlunoId = new SelectList(_alunoRepository.GetAll(), "AlunoId", "Nome");

            var aluno = _alunoRepository.GetById(AlunoId);
            aluno.TreinoId = TreinoId;
            _alunoRepository.Update(aluno);
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("beforza", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Treinos", "Index", "Treino", new { area = "" }, null)</li>                   
                    <li>@Html.ActionLink("Alunos", "Index", "Aluno", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Exercícios", "Index", "Exercicio", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Treino/Aluno", "TreinoToAluno", "Treino", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Relatórios", "", "", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - beforza</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>